- name: test fail module
  hosts: all

  tasks:
    - name: create a user
      user:
        name: y1
        state: present
      register: r2
    - name: debug r2
      debug:
        var: r2
    - name: check cpu count
      debug:
        msg: "cpu cores availbale in {{ ansible_host }} number of cpcu cores {{ ansible_processor_cores }}"
    - name: create a failure task to create if cpu cores less then 8 make it ha failed
      fail:
        msg: "the system dont have enough cores to work on it due to this it is not ppossible"
      when: ansible_processor_cores < 8
      ignore_errors: true
    - name: use commond module
      command: /bin/uptime
      register: r1
    - name: debug info
      debug:
        var: r1

